### ISSUE TITLE
Consider Adding Removal/Index by Reference

### ISSUE THREAD

**Issue by dave-fl** [orxfun/orx-linked-list#17]
Would it be possible to expose the underlying `Node<T>` and also provide functions for insert/removal and index based on the reference itself rather than index number in the list.  The intent would be to allow the operations to perform in O(1) time.

It would be the callees responsibility to maintain a reference to the `Node<T>` after a value is inserted.

**Comment by orxfun** [comment]
Hey @dave-fl . I was busy with a major revision, but now I can focus on this issue. Thank you for the issue by the way, this makes complete sense.

We might not return exactly the `Node<T>` directly though as it could expose `&` references which could break safety. But alternatively we can return some sort of a key, let's say `Key` for now, to the node.

# Good Case

With some made up methods, the use could be something like:

```rust
orx_linked_list::*;

let mut list = DoublyLinkedList::from_iter(['a', 'b', 'c']);

let key_x: Key = list.append_back('x'); // the list is a-b-c-x

list.append_back('d');
list.append_back('e');  // the list is a-b-c-x-d-e

// then we can insert a node previous to x in O(1)
list.insert_prev_to(key_x, 'w');  // the list is a-b-c-w-x-d-e

// or next to x in O(1)
list.insert_next_to(key_x, 'y');  // the list is a-b-c-w-x-y-d-e

// and we can remove x in O(1)
list.remove(key_x);  // the list is a-b-c-w-y-d-e
```

The code above would work perfectly fine. There could be problems; however, when we start removing elements from the list. 

# Problem Case

Using a lazy removal to have an amortized constant time, removal leave sort of holes in the underlying data structure. If the amount of holes exceed a threshold; or more precisely when the utilization of the memory falls below a constant threshold, the list automatically arranges its elements and reclaims the not utilized memory. This could invalidate the keys.

Assume that the threshold is 75%.

```rust
use orx_linked_list::*;

let mut list = DoublyLinkedList::from_iter(['a', 'b', 'c', 'd']); // util = 4/4 =100%

let key_x = list.append_back('x'); // the list is a-b-c-d-x ; util = 5 / 5 = 100%

_ = list.pop_front();  // the list is *-b-c-d-x ; util = 4 / 5 = 80%

_ = list.pop_front(); 
// the list first becomes *-*-c-d-x ; util = 3 / 5 = 60% < 75% -> triggers memory reclaim
// then the list becomes c-d-x ; 3 / 3 = 100%
```

After the last `pop_front()`, we no longer have a valid key `key_x` pointing to `x`. We can argue that this problem is no different than the following problem with a standard vector.

```rust
let mut vec = vec!['a', 'b', 'c'];

vec.push('x'); // a-b-c-x
let key_x = vec.len() - 1; // index 3 of x is analogous to our key to element x

vec.push('d');  // a-b-c-x-d

vec.remove(0); // b-c-x-d
// our key, key_x, is already invalidated ; vec[key_x] now is now pointing to wrong element, 'd'

vec.remove(0); // c-x-d ; key_x is now not a valid key for the vec, it is out of bounds.

// this panics
vec.remove(key_x);
```

# Possible Directions

1. So standard vector leaves the responsibility to the caller, as you suggested. We can also follow a similar approach. But I think we could at least know and give feedback to the caller that the key is not valid anymore.
2. Or we can have a hybrid approach as follows. If no memory reclaims happened in between, we directly do the insertion/removal in O(1). Otherwise, we attempt to fix the key and still perform the operation in O(n).
3. Lastly, we now use [`orx_selfref_col:SelfRefCol`](https://crates.io/crates/orx-selfref-col) as the underlying storage which provides two strategies for reclaiming memory:
  * `MemoryReclaimOnThreshold<D>` where `D` determines the utilization threshold,
  * `MemoryReclaimNever` which never reclaims the holes.
* The problem case above  would never be observed with `MemoryReclaimNever`; all references/keys would be valid for the entire lifetime of the list. But the drawback is that it is not as memory efficient especially when there are a significant number of removals from the list. Currently, linked list uses `MemoryReclaimOnThreshold<2>` as a fixed value of the generic type. So the third option could be to bring these two options from `SelfRefCol` to the linked list. The caller can decide which one to use. And we can provide insert, remove and more operations relying on correctness of the references in O(1) for the `MemoryReclaimNever` variant. Besides, we can still allow to manually reclaim memory giving responsibility to the caller such that:
  * if you do not manually reclaim, all keys will always be valid;
  * if you reclaim, they are invalidated.

Seems like this is an important milestone and the ideas need to cook a little together with the revision. I will be thinking on it. Meanwhile, please provide your feedback, corrections or examples, they would be super helpful.

**Comment by orxfun** [comment]
`SelfRefCol` made available the `NodeIndex` here [https://github.com/orxfun/orx-selfref-col/pull/3](https://github.com/orxfun/orx-selfref-col/pull/3). Revising methods adding elements to the linked list to return a `NodeIndex` which would allow constant time access.
