### ISSUE TITLE
question: push_front complexity

### ISSUE THREAD

**Issue by dzmitry-lahoda** [orxfun/orx-linked-list#27]
`push_front` tells O(1). is it average case or worst case?

by worst i mean there is some vector backing storage which may be extended? so all elements need to be copied? in this case $O(n)$, but average is $\Theta(1)$.

**Comment by orxfun** [comment]
That's a good point @dzmitry-lahoda . As you said there is a backing vector; however, it is a [`SplitVec`](https://github.com/orxfun/orx-split-vec) which is a [`PinnedVec`](https://github.com/orxfun/orx-pinned-vec) implementation. This is relevant because pinned vectors' growth is copy-free.

To be precise in the complexity of methods, it would be better to split operations in two sets.

# Push

`push_front` and `push_back` are truly $\Theta(1)$:
* If the backing vector has room for the new element, it is pushed to the vector, one or two references are updated depending whether or not it is a `Singly` or `Doubly` linked list. And that is it.
* If the backing vector is at capacity, it will allocate additional memory. Already pushed elements remain at their prior locations (hence, pinned), no copies happen. Therefore, this operation is independent of the number of elements in the list, therefore, also a constant time operation. Then, again the new element is pushed to the vector, one or two links are udpated.

# Pop

Removing from the list by pop methods are lazy. In other words, they take the value out, update one-or-two  references, return the value to the caller. So far these methods are also $\Theta(1)$.

As you may imagine, this might lead to inefficient memory usage when there exist many pops. For instance, consider a scenario where we push 1 million (1m) elements to the list, so we end up with an allocated memory of at least 1m positions in the backing vector. Then, we pop all of them. At this point, we would end up with an allocation of 1m positions which are empty.

Therefore, the linked list has an additional generic argument for memory reclaim policy, to give the choice to the user. Note that each memory reclaim operation has linear time $\Theta(n)$ and will immediately increase memory utilization to 100%.

You may achieve a constant time for all pop operations, an amortized constant time, or any level of time complexity with a manual call of memory reclaim calls when it is very critical.

## Memory Reclaim On Threshold (Default)

* `DoublyLinkedList<T, M = MemoryReclaimOnThreshold<2>> = List::<Doubly<MemoryReclaimOnThreshold<2>>, T>`
* `SinglyLinkedList<T, M = MemoryReclaimOnThreshold<2>> = List::<Singly<MemoryReclaimOnThreshold<2>>, T>`

[from-docs](https://docs.rs/orx-linked-list/latest/orx_linked_list/struct.MemoryReclaimOnThreshold.html) 

A `MemoryReclaimPolicy` which reclaims all closed nodes whenever the utilization falls below a threshold.

The threshold is a function of the constant generic parameter `D`.
Specifically, memory of closed nodes will be reclaimed whenever the ratio of closed nodes to all nodes exceeds one over `2^D`.
* when `D = 0`: memory will be reclaimed when utilization is below 0.00% (equivalent to never).
* when `D = 1`: memory will be reclaimed when utilization is below 50.00%.
* when `D = 2`: memory will be reclaimed when utilization is below 75.00%.
* when `D = 3`: memory will be reclaimed when utilization is below 87.50%.
* when `D = 4`: memory will be reclaimed when utilization is below 93.75%.

***Regarding your question: this policy will lead to amortized constant time for pop methods.***

## Never Reclaim Memory

* `DoublyLinkedList<T, M = MemoryReclaimNever> = List::<Doubly<MemoryReclaimNever>, T>`
* `SinglyLinkedList<T, M = MemoryReclaimNever> = List::<Singly<MemoryReclaimNever>, T>`

[from-docs](https://docs.rs/orx-linked-list/latest/orx_linked_list/struct.MemoryReclaimNever.html) 

A do-nothing MemoryReclaimPolicy which would never reclaim the memory of the closed nodes, leaving them as holes in the underlying storage.

This approach has the advantage that a NodeIndex is never invalidated due to an automatic memory reorganization.

Furthermore, node utilization can still be maximized by manually calling `reclaim_closed_nodes` method.

***Regarding your question: this policy will lead to constant time for all pop calls.***
